# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#patreon: fixator10 # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
#ko_fi: fixator10 # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
custom:
#  - "https://paypal.me/fixator10"
  - "https://vk.me/moneysend/fixator10"
  - "https://steamcommunity.com/tradeoffer/new/?partner=81122783&token=YQ3cE9s0"
  - "https://boosty.to/fixator10"
  - "https://www.donationalerts.com/r/fixator10"
