contact_links:
  - name: Direct Contact
    url: https://fixator10.ru/
    about: You can use one of contacts listed there to contact me.
  - name: Red - Cog Support Discord Server
    url: https://discord.gg/GET4DVk
    about: You can also find me (Fixator10#7133) here.
  - name: Discussions
    url: https://github.com/fixator10/Fixator10-Cogs/discussions
    about: Or just start a discussion on GitHub, if you have questions.
