name: isort

on: [push, pull_request]


jobs:
  mypy:
    name: Style Check with Isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.8"
      - run: "python -m pip install isort"
        name: Install isort
      - run: "python -m isort --check-only --diff --profile black -l 99 ."
        name: Style checking with isort

# thanks sinbad & jack
